
--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t machineinfodemo  . "
      - "docker tag machineinfodemo 543816070942.dkr.ecr.us-east-1.amazonaws.com/cybage_devops_ecrrepo_neha:v1.1.2"
  install: 
    runtime-versions: 
      docker: 18
  post_build: 
    commands: 
      - "docker push 543816070942.dkr.ecr.us-east-1.amazonaws.com/cybage_devops_ecrrepo_neha:v1.1.2"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - " $(aws ecr get-login --no-include-email --region us-east-1)"
version: 0.2
